# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'XMYLFM' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!


pod 'AFNetworking'
pod 'SDWebImage'
pod 'MJRefresh'
  # Pods for XMYLFM

  target 'XMYLFMTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'XMYLFMUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
